### ISSUE TITLE
Endianness and other portability questions

### ISSUE THREAD

**Issue by denisdemaisbr** [svaarala/lowzip#4]
Hi!

1) this library are safe with:
1.0) cpu big-endian ?
1.1) compiller 16,32,64-bits ?
2) maybe usage support to zlib*
3) can add more examples =)

note: can be more portable; some 'zip' library usage #pack pragma
http://man7.org/linux/man-pages/man3/endian.3.html
http://man7.org/linux/man-pages/man3/byteorder.3.html

**Comment by svaarala** [comment]
Off-hand don't see a reason why it wouldn't work on a big endian target. There are some type assumptions in place, see lowzip.c comments.

I don't think zlib support would make much sense: the goal of this library is to be a tiny ZIP reader that can be just included in a build with no further hassle. I'm using it for loading Javascript and asset files from ZIP files on very small embedded targets. There are a lot of different ZIP libraries already out there for more general purpose use :)

What examples would you like to see?

**Comment by denisdemaisbr** [comment]
about support zlib, i.e., save some data code sharing a in use zlib program.

some specs of zip file are endianess based*, then, using some "endianess" features macros like endian.h can be more portable about big-endian cpu ( I'm use arm9/11 32-bit big-endian )

a feature request an "virtual filesystem" interface-like

examples; file iterator (dump file list + size + compress method) ; if is a valid zip file 

* zip file format
https://gist.github.com/LuChang-CS/c20eeeb0a715fcea10f13175b54b2216
https://en.wikipedia.org/wiki/Zip_(file_format)
http://www.onicos.com/staff/iz/formats/zip.html

---
i was download the project and will contrib with some examples e reports!

**Comment by svaarala** [comment]
The file format is endian dependent but the lowzip just handles it "manually", e.g.: https://github.com/svaarala/lowzip/blob/master/lowzip.c#L143-L175. This avoids endianness and alignment issues.

**Comment by denisdemaisbr** [comment]
pretty good !

look at: http://mirror.fsf.org/pmon2000/2.x/src/sys/sys/endian.h 
(same aproach used at bsd sockets)

**Comment by svaarala** [comment]
Right, but I don't want to rely on any endianness headers - their name changes across platforms and they aren't always available.
